"""empty message

Revision ID: f090ce3c1c58
Revises: 
Create Date: 2020-05-04 22:04:54.454369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f090ce3c1c58"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artist",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=15), nullable=False),
        sa.Column("last_name", sa.String(length=25), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=120), nullable=False),
        sa.Column("zip_code", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("artist_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "category",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_table(
        "status",
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("status_type", sa.String(length=20), nullable=False),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("status_id"),
    )
    op.create_table(
        "art",
        sa.Column("art_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("art_location", sa.String(), nullable=False),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["category.category_id"],),
        sa.PrimaryKeyConstraint("art_id"),
    )
    op.create_table(
        "instructor",
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artist.artist_id"],),
        sa.PrimaryKeyConstraint("instructor_id"),
    )
    op.create_table(
        "parent",
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artist.artist_id"],),
        sa.PrimaryKeyConstraint("parent_id"),
    )
    op.create_table(
        "payment_method",
        sa.Column("payment_method_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(), nullable=False),
        sa.Column("stripe_payment_method_id", sa.String(), nullable=False),
        sa.Column("payment_type", sa.String(length=10), nullable=False),
        sa.Column("last_4", sa.Integer(), nullable=False),
        sa.Column("exp_month", sa.Integer(), nullable=False),
        sa.Column("zip_code", sa.String(), nullable=False),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artist.artist_id"],),
        sa.PrimaryKeyConstraint("payment_method_id"),
        sa.UniqueConstraint("stripe_customer_id"),
    )
    op.create_table(
        "artist_art",
        sa.Column("artist_art_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("art_id", sa.Integer(), nullable=False),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["art_id"], ["art.art_id"],),
        sa.ForeignKeyConstraint(["artist_id"], ["artist.artist_id"],),
        sa.PrimaryKeyConstraint("artist_art_id"),
    )
    op.create_table(
        "child",
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("date_of_birth", sa.DateTime(), nullable=False),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artist.artist_id"],),
        sa.ForeignKeyConstraint(["parent_id"], ["parent.parent_id"],),
        sa.PrimaryKeyConstraint("child_id"),
    )
    op.create_table(
        "payment_instance",
        sa.Column("payment_instance_id", sa.Integer(), nullable=False),
        sa.Column("payment_method_id", sa.Integer(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_method_id"], ["payment_method.payment_method_id"],
        ),
        sa.PrimaryKeyConstraint("payment_instance_id"),
    )
    op.create_table(
        "workshop",
        sa.Column("workshop_id", sa.Integer(), nullable=False),
        sa.Column("instructor_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("video_loc", sa.String(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("max_class_size", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("scheduled_dt", sa.DateTime(), nullable=False),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["category.category_id"],),
        sa.ForeignKeyConstraint(["instructor_id"], ["instructor.instructor_id"],),
        sa.ForeignKeyConstraint(["status_id"], ["status.status_id"],),
        sa.PrimaryKeyConstraint("workshop_id"),
    )
    op.create_table(
        "workshop_child",
        sa.Column("workshop_child_id", sa.Integer(), nullable=False),
        sa.Column("workshop_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("inserted_dt", sa.DateTime(), nullable=False),
        sa.Column("updated_dt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["child_id"], ["child.child_id"],),
        sa.ForeignKeyConstraint(["workshop_id"], ["workshop.workshop_id"],),
        sa.PrimaryKeyConstraint("workshop_child_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workshop_child")
    op.drop_table("workshop")
    op.drop_table("payment_instance")
    op.drop_table("child")
    op.drop_table("artist_art")
    op.drop_table("payment_method")
    op.drop_table("parent")
    op.drop_table("instructor")
    op.drop_table("art")
    op.drop_table("status")
    op.drop_table("category")
    op.drop_table("artist")
    # ### end Alembic commands ###
